### ISSUE TITLE
Broken setup.py

### ISSUE THREAD

**Issue by mmiladi** [fabriziocosta/EDeN#124]
steup.py needs to be updated according to latest separations of eden and eden_rna..

Error log is:

```
 setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/eden
copying eden/sequence.py -> build/lib/eden
copying eden/__init__.py -> build/lib/eden
copying eden/graph.py -> build/lib/eden
copying eden/util.py -> build/lib/eden
error: package directory 'eden/util' does not exist
Traceback (most recent call last):
  File "/home/milad/miniconda2/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/milad/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "/home/milad/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "/home/milad/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/home/milad/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1480, in build_tree
    config=config)
  File "/home/milad/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1059, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/home/milad/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 592, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/home/milad/miniconda2/lib/python2.7/site-packages/conda_build/utils.py", line 588, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/home/milad/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/home/milad/miniconda2/conda-bld/eden_1486481741988/work/EDeN-master/conda_build.sh']' returned non-zero exit status 1

```

**Comment by fabriziocosta** [comment]
fized
